[build]
  builder = "nixpacks"

[deploy]
  startCommand = "python api_proxy_server.py --port $PORT"
  healthcheckPath = "/"
  healthcheckTimeout = 60
  restartPolicyType = "on-failure"
  restartPolicyMaxRetries = 3

[env]
  WEB_DIR = "build/web"
  PYTHONUNBUFFERED = "1"
